---
# tasks file for roles/bitlocker-off
- name: Determine whether bitlocker installed (green) or not (yellow)
  win_shell: (Get-WindowsFeature -Name Bitlocker).Installed
  register: bitlockerinstalled
  changed_when: not bitlockerinstalled.stdout_lines[0]|bool
- name: Determine current bitlocker status
  win_shell: (get-psdrive -PSProvider FileSystem).root | get-bitlockervolume
  register: bitlockerprestatus
  changed_when: false
  when: bitlockerinstalled.stdout_lines[0]|bool
- name: Enumerate all filesystem drives and turn off bitlocker
  win_shell: (get-psdrive -PSProvider FileSystem).root | suspend-bitlocker
  register: bitlockeroff
  changed_when: bitlockerprestatus.stdout_lines != bitlockeroff.stdout_lines
  when: bitlockerinstalled.stdout_lines[0]|bool
