---
# tasks file for roles/win-logons-disable
- name: check current state
  win_shell: change logon /query
  register: query
  changed_when: false
  failed_when: query.rc > 1
- name: disable RDP logins
  win_shell: change logon /disable
  register: disable
  changed_when: disable.stderr != query.stderr
  failed_when: disable.rc > 1
