---
- hosts: "{{ target }}"
  name: Install Updates and Reboot
  vars_prompt:
    - name: target
      prompt: "Enter host(s) or group(s), comma-separated"
      private: no
  vars:
    wu_reboot: "yes"
    wu_state: "installed"
    all_users: true
  roles:
    - role: win-logons
      vars:
        logon_state: disabled
    - win-log-everyone-off
    - role: win-bitlocker
      vars:
        bitlocker_state: suspend
    - win-choco-update-install
    - win-wu-universal
    - role: win-bitlocker
      vars:
        bitlocker_state: resume
    - role: win-logons
      vars:
        logon_state: enabled
